export const categories = [
  { id: 'dogs', label: 'Dogs', text: 'Breeds, habits, temperament, daily care and living needs.' },
  { id: 'cats', label: 'Cats', text: 'Cat breeds, behavior, enrichment, grooming and everyday care.' },
  { id: 'birds', label: 'Birds', text: 'Companion birds plus bird profiles for learning and observation.' },
  { id: 'small-animals', label: 'Small animals', text: 'Rabbits, guinea pigs, hamsters, rats and other companion animals.' },
  { id: 'fish-aquatic', label: 'Fish & aquatic', text: 'Freshwater fish, aquarium habits and responsible aquatic care.' },
  { id: 'reptiles', label: 'Reptiles', text: 'Popular companion reptiles and the basics of responsible husbandry.' },
];

const item = (id, type, name, meta, description, tags, habits, dailyCare, related = [], featured = false, note = '') => ({ id, type, name, meta, description, tags, habits, dailyCare, related, featured, note });

export const records = [
  item('labrador-retriever','dogs','Labrador Retriever','Dog breed · Sporting','Friendly, adaptable and energetic companion known for a strong retrieving instinct and enthusiasm for family activities.',['Friendly','Active','Trainable'],'Often social, food-motivated and eager to participate; many enjoy retrieving, swimming and interactive games.','Daily exercise, training games, fresh water, routine coat care and regular social interaction.',['golden-retriever','beagle','border-collie'],true),
  item('golden-retriever','dogs','Golden Retriever','Dog breed · Sporting','Affectionate, people-oriented breed with a reputation for trainability and a love of outdoor activity.',['Friendly','Active','Family'],'Usually enjoys human company, carrying objects, retrieving games and learning cooperative tasks.','Daily walks and play, mental enrichment, brushing and consistent training.',['labrador-retriever','cavalier-king-charles-spaniel','border-collie'],true),
  item('german-shepherd','dogs','German Shepherd','Dog breed · Working','Athletic, intelligent working breed often valued for learning complex tasks and forming close bonds with handlers.',['Intelligent','Working','Active'],'Alert and task-oriented; often benefits from structured activities and clear routines.','Physical exercise plus training and problem-solving activities; regular brushing and socialization.',['belgian-malinois','border-collie','rottweiler']),
  item('border-collie','dogs','Border Collie','Dog breed · Herding','Highly energetic herding breed known for learning quickly and responding closely to human cues.',['Very active','Intelligent','Herding'],'Often seeks movement and mental work; herding behaviors can appear as intense attention to motion.','Substantial daily physical activity, training, puzzle games and opportunities to use natural problem-solving skills.',['australian-shepherd','german-shepherd','labrador-retriever']),
  item('beagle','dogs','Beagle','Dog breed · Hound','Curious scent hound with a lively personality and a strong interest in following smells.',['Curious','Scent-driven','Social'],'Uses its nose extensively and can become absorbed in interesting scents or food smells.','Secure outdoor exercise, scent games, routine training and careful food management.',['labrador-retriever','dachshund','cavalier-king-charles-spaniel']),
  item('dachshund','dogs','Dachshund','Dog breed · Hound','Small, distinctive hound originally developed for working around burrows and tracking quarry.',['Small','Curious','Scent-driven'],'Often confident and inquisitive, with strong interest in exploring smells and investigating spaces.','Moderate daily activity, controlled jumping, training and routine grooming suited to coat type.',['beagle','corgi','miniature-schnauzer']),
  item('poodle','dogs','Poodle','Dog breed · Companion / Sporting','Intelligent breed available in several size varieties and known for a curly, continuously growing coat.',['Intelligent','Trainable','Low-shedding coat'],'Often enjoys learning tricks, structured games and close interaction with people.','Daily mental and physical activity plus frequent coat maintenance and professional grooming as needed.',['bichon-frise','cavalier-king-charles-spaniel','border-collie']),
  item('french-bulldog','dogs','French Bulldog','Dog breed · Companion','Compact companion breed recognized for a distinctive appearance and generally affectionate household temperament.',['Companion','Compact','Indoor'],'Often prefers people-centered activities and shorter play sessions rather than prolonged strenuous exercise.','Moderate activity, heat awareness, healthy weight, and routine skin, ear and dental care.',['pug','cavalier-king-charles-spaniel','boston-terrier']),
  item('cavalier-king-charles-spaniel','dogs','Cavalier King Charles Spaniel','Dog breed · Companion','Small companion breed known for an affectionate temperament and willingness to participate in family life.',['Affectionate','Companion','Adaptable'],'Often follows people around the home and enjoys gentle play and walks.','Daily walks, social interaction, brushing and routine veterinary care.',['golden-retriever','poodle','beagle']),
  item('corgi','dogs','Pembroke Welsh Corgi','Dog breed · Herding','Compact herding breed with an energetic personality and a strong tendency to stay engaged with its household.',['Herding','Energetic','Alert'],'Can be playful, observant and persistent; many enjoy learning structured tasks.','Daily exercise, training, puzzle activities and regular brushing during shedding periods.',['dachshund','border-collie','australian-shepherd']),
  item('australian-shepherd','dogs','Australian Shepherd','Dog breed · Herding','Athletic herding breed known for intelligence, energy and a close working relationship with people.',['Active','Intelligent','Herding'],'Often thrives on movement, learning and activities that provide a clear purpose.','Daily physical exercise, training, enrichment and coat care.',['border-collie','corgi','german-shepherd']),
  item('rottweiler','dogs','Rottweiler','Dog breed · Working','Powerful working breed known for confidence, strength and strong bonds with its household when well socialized and trained.',['Strong','Working','Trainable'],'Often attentive and steady, benefiting from predictable routines and constructive training.','Daily controlled exercise, positive training, socialization and regular grooming.',['german-shepherd','labrador-retriever']),
  item('bichon-frise','dogs','Bichon Frisé','Dog breed · Companion','Small companion breed with a cheerful personality and a soft curly coat that needs regular maintenance.',['Small','Cheerful','Companion'],'Usually social and playful, often enjoying short games and close human interaction.','Daily play and walks, regular brushing and professional grooming.',['poodle','maltese','cavalier-king-charles-spaniel']),
  item('maltese','dogs','Maltese','Dog breed · Companion','Small companion dog recognized for a long, silky coat and people-oriented nature.',['Small','Companion','Long coat'],'Often enjoys attention, lap time and short periods of playful activity.','Gentle daily activity, frequent coat care, dental hygiene and social interaction.',['bichon-frise','cavalier-king-charles-spaniel']),
  item('siberian-husky','dogs','Siberian Husky','Dog breed · Working','Athletic northern breed developed for endurance and movement in cold climates.',['Athletic','Endurance','Independent'],'Often energetic, curious and motivated to explore; many enjoy running and active outdoor time.','Substantial daily exercise, secure outdoor arrangements, coat care and mental enrichment.',['alaskan-malamute','border-collie']),

  item('maine-coon','cats','Maine Coon','Cat breed · Long-haired','Large domestic cat known for a social temperament, tufted appearance and substantial coat.',['Large','Social','Long-haired'],'Often curious and people-aware while retaining typical feline independence.','Daily interaction, regular brushing, scratching opportunities and vertical spaces.',['ragdoll','norwegian-forest-cat','british-shorthair'],true),
  item('ragdoll','cats','Ragdoll','Cat breed · Long-haired','Large semi-long-haired cat known for a generally relaxed and people-oriented temperament.',['Gentle','Social','Long-haired'],'Often seeks companionship and enjoys calm interactive play.','Regular brushing, interactive play, scratching surfaces and comfortable resting places.',['maine-coon','birman','british-shorthair']),
  item('british-shorthair','cats','British Shorthair','Cat breed · Short-haired','Stocky short-haired cat known for a calm, steady presence and dense plush coat.',['Calm','Short-haired','Adaptable'],'Often enjoys being near people without demanding constant attention.','Interactive play, scratching areas, coat brushing and a healthy routine.',['ragdoll','russian-blue','maine-coon']),
  item('siamese','cats','Siamese','Cat breed · Short-haired','Social, vocal cat breed known for close interaction with people and an athletic build.',['Vocal','Social','Active'],'Often seeks communication and attention and may become bored without interaction.','Daily interactive play, climbing opportunities, puzzle feeding and companionship.',['oriental-shorthair','burmese','abyssinian']),
  item('persian','cats','Persian','Cat breed · Long-haired','Long-haired cat breed known for a calm household presence and distinctive coat and facial features.',['Calm','Long-haired','Indoor'],'Often prefers predictable environments and comfortable resting areas.','Frequent coat grooming, eye-area hygiene as appropriate, indoor enrichment and routine veterinary care.',['ragdoll','british-shorthair','exotic-shorthair']),
  item('bengal','cats','Bengal','Cat breed · Short-haired','Athletic cat breed known for high activity levels, curiosity and a distinctive spotted or marbled coat.',['Active','Curious','Athletic'],'Often climbs, investigates and seeks interactive challenges.','Vertical space, vigorous interactive play, puzzle feeding and environmental enrichment.',['abyssinian','siamese']),
  item('abyssinian','cats','Abyssinian','Cat breed · Short-haired','Active, curious cat breed known for an athletic build and strong interest in exploration.',['Active','Curious','Short-haired'],'Often investigates elevated spaces and enjoys interactive activities.','Daily play, climbing structures, scratching surfaces and safe exploration.',['bengal','siamese','oriental-shorthair']),
  item('scottish-fold','cats','Scottish Fold','Cat breed · Short-haired','Recognizable cat breed with folded ears resulting from a genetic mutation; welfare considerations are important when discussing the breed.',['Companion','Short-haired','Welfare-aware'],'Temperament varies by individual; many enjoy calm household interaction.','Routine play, scratching options and regular veterinary oversight. Breed welfare should be discussed carefully because the same mutation is associated with cartilage and skeletal problems.',['british-shorthair','ragdoll']),
  item('russian-blue','cats','Russian Blue','Cat breed · Short-haired','Elegant short-haired breed known for a dense blue-gray coat and often reserved but affectionate behavior.',['Quiet','Short-haired','Observant'],'May prefer predictable routines and can take time to warm to unfamiliar people.','Interactive play, quiet resting places, scratching surfaces and gentle social interaction.',['british-shorthair','siamese']),
  item('birman','cats','Birman','Cat breed · Semi-long-haired','Semi-long-haired companion cat known for color-point markings and a generally gentle household temperament.',['Gentle','Social','Semi-long-haired'],'Often enjoys companionship and interactive but moderate play.','Regular brushing, play sessions, climbing options and social interaction.',['ragdoll','siamese','maine-coon']),
  item('oriental-shorthair','cats','Oriental Shorthair','Cat breed · Short-haired','Slender, athletic breed closely related to the Siamese type and known for social interaction.',['Social','Vocal','Athletic'],'Often wants involvement in household activity and may vocalize to communicate.','Daily interactive play, climbing structures and consistent companionship.',['siamese','abyssinian','bengal']),
  item('exotic-shorthair','cats','Exotic Shorthair','Cat breed · Short-haired','Short-haired companion breed developed from Persian-type cats, with a plush coat and generally calm household style.',['Calm','Short-haired','Companion'],'Often enjoys quiet companionship and gentle play.','Regular brushing, indoor enrichment and attention to breathing or heat tolerance where relevant to individual conformation.',['persian','british-shorthair','ragdoll']),

  item('budgerigar','birds','Budgerigar','Companion bird · Parakeet','Small Australian parrot commonly kept as a companion bird and known for social behavior and vocal communication.',['Small parrot','Social','Vocal'],'Active during the day, enjoys climbing, chewing, exploring and communicating with flock members.','Fresh food and water, enclosure cleaning, safe flight or exercise time, enrichment and social interaction.',['cockatiel','canary','finch'],true),
  item('cockatiel','birds','Cockatiel','Companion bird · Parrot','Gentle Australian parrot known for whistles, crest movements and strong social bonds.',['Parrot','Social','Vocal'],'Often whistles, explores and seeks interaction while maintaining periods of quiet rest.','Fresh food and water, daily enrichment, safe exercise, cleaning and social interaction.',['budgerigar','conure','canary']),
  item('canary','birds','Canary','Companion bird · Songbird','Small songbird valued for vocalizations and relatively independent behavior compared with parrots.',['Songbird','Small','Vocal'],'Often spends time perching, moving between levels and singing in comfortable environments.','Fresh water, balanced diet, clean enclosure, appropriate perches and calm surroundings.',['finch','budgerigar','zebra-finch']),
  item('zebra-finch','birds','Zebra Finch','Companion bird · Finch','Small social finch known for active movement and distinctive vocal communication.',['Finch','Social','Active'],'Often thrives in compatible social groups and spends much of the day moving, feeding and vocalizing.','Clean enclosure, suitable perches, fresh water, appropriate diet and social enrichment.',['canary','budgerigar']),
  item('green-cheek-conure','birds','Green-cheeked Conure','Companion bird · Parrot','Small parrot known for playfulness, curiosity and close interaction with people.',['Parrot','Playful','Social'],'Often climbs, chews, explores and seeks interactive play.','Safe enrichment, chewable toys, fresh food and water, cleaning and supervised out-of-cage activity.',['cockatiel','budgerigar','lovebird']),
  item('lovebird','birds','Lovebird','Companion bird · Parrot','Small, active parrots known for strong social bonds and energetic behavior.',['Parrot','Social','Active'],'Often explores intensely, plays with objects and forms strong bonds with companions.','Daily enrichment, safe exercise, fresh food and water and appropriate social companionship.',['budgerigar','green-cheek-conure','cockatiel']),
  item('african-grey','birds','African Grey Parrot','Companion bird · Parrot','Highly intelligent parrot known for complex vocal learning and strong cognitive engagement.',['Parrot','Highly intelligent','Social'],'Often investigates objects and environments and benefits from meaningful interaction.','Substantial enrichment, safe exercise, varied appropriate diet, routine and significant social interaction.',['cockatiel','green-cheek-conure']),
  item('pigeon','birds','Domestic Pigeon','Companion bird · Columbidae','Domesticated pigeon varieties can form close bonds with people and have a long history of human association.',['Social','Intelligent','Bird'],'Often explores, walks and flies when given safe opportunities and can recognize familiar routines.','Clean living space, fresh water, suitable diet, safe exercise and regular sanitation.',['dove','swallow']),
  item('dove','birds','Domestic Dove','Companion bird · Columbidae','Gentle domesticated dove varieties can be calm companion birds when provided with appropriate housing and care.',['Gentle','Social','Bird'],'Often spends time perching, walking and quietly interacting with its environment.','Clean enclosure, fresh water, appropriate diet, perches and safe exercise.',['pigeon','canary','swallow']),
  item('swallow','birds','Swallows','Wild bird · Hirundinidae','Fast-flying migratory birds adapted to catching insects in the air; swallows are generally wild birds rather than household pets.',['Wild bird','Migratory','Insect-eating'],'Often forage in open airspace, gather around suitable habitats and migrate seasonally.','Best cared for through habitat protection, avoiding disturbance of nests and supporting healthy insect-rich ecosystems rather than keeping them as pets.',['pigeon','dove','birdwatching'],false,'Swallows should be treated as wildlife. A wild swallow should not be taken from the wild or kept as a household pet. For an injured wild bird, contact a licensed wildlife rehabilitator or appropriate local authority.'),
  item('birdwatching','birds','Birdwatching','Bird activity · Wildlife','A respectful way to observe wild birds and learn about behavior, migration, calls and habitats without keeping them captive.',['Wildlife','Observation','Nature'],'Birds can be observed feeding, nesting, bathing, communicating and migrating according to species and season.','Keep distance from nests, avoid disturbing wildlife, use quiet observation practices and protect habitat.',['swallow','pigeon','dove']),

  item('holland-lop','small-animals','Holland Lop','Rabbit breed · Companion','Small lop-eared rabbit breed often kept as a companion and known for a compact appearance.',['Rabbit','Social','Small'],'Rabbits are active, curious and social, with periods of energetic exploration and rest.','Unlimited grass hay, suitable fresh foods, clean water, safe exercise space, hiding places and routine grooming.',['netherland-dwarf','guinea-pig'],true),
  item('netherland-dwarf','small-animals','Netherland Dwarf','Rabbit breed · Companion','Very small rabbit breed with a compact body and alert personality.',['Rabbit','Small','Active'],'Often curious and quick to investigate new surroundings.','A generous exercise area despite small body size, abundant hay, safe chew options, fresh water and gentle handling.',['holland-lop','guinea-pig']),
  item('guinea-pig','small-animals','Guinea Pig','Small mammal · Companion','Social herbivorous small mammal that communicates through vocalizations and body language.',['Social','Herbivore','Small mammal'],'Often active in short bursts, vocal when anticipating food and more comfortable with compatible companionship.','Constant access to grass hay, fresh water, species-appropriate vitamin C sources, clean bedding and daily movement.',['holland-lop','hamster','rat'],true),
  item('syrian-hamster','small-animals','Syrian Hamster','Small mammal · Hamster','Solitary hamster species commonly kept as a companion animal and known for nocturnal activity.',['Nocturnal','Solitary','Small mammal'],'Usually most active in the evening and night, with digging, storing and exploring behaviors.','Appropriately deep bedding for burrowing, enrichment, fresh water, suitable diet and a properly sized solid exercise wheel.',['dwarf-hamster','gerbil']),
  item('dwarf-hamster','small-animals','Dwarf Hamster','Small mammal · Hamster','Group of small hamster species with active exploratory behavior and housing needs that vary by species.',['Nocturnal','Small','Active'],'Often digs, forages, stores food and explores after dark.','Deep bedding, enrichment, safe wheel, fresh water and species-appropriate housing; check compatibility carefully before co-housing.',['syrian-hamster','gerbil']),
  item('fancy-rat','small-animals','Fancy Rat','Small mammal · Companion','Domesticated rat known for intelligence, social behavior and strong curiosity.',['Intelligent','Social','Small mammal'],'Often investigates objects, learns routines and seeks social interaction.','Compatible companionship, enrichment, clean housing, fresh water, balanced food and daily opportunities to explore safely.',['guinea-pig','gerbil']),
  item('gerbil','small-animals','Mongolian Gerbil','Small mammal · Companion','Small social rodent known for digging, burrowing and active exploration.',['Social','Burrowing','Small mammal'],'Often spends time digging tunnels, investigating scents and interacting with compatible companions.','Deep appropriate bedding, enrichment, fresh water, balanced diet and secure housing.',['dwarf-hamster','fancy-rat']),
  item('chinchilla','small-animals','Chinchilla','Small mammal · Companion','Small South American rodent with extremely dense fur and a strong need for a cool, dry environment.',['Nocturnal','Dense fur','Heat-sensitive'],'Often most active around evening and night and enjoys jumping and exploring.','Cool environment, dust-bathing material designed for chinchillas, safe climbing space, hay and appropriate diet.',['guinea-pig','fancy-rat']),
  item('ferret','small-animals','Ferret','Small mammal · Companion','Curious domesticated mustelid known for playful exploration, digging and complex social behavior.',['Playful','Curious','Social'],'Often sleeps for long periods but becomes highly active during waking periods, exploring and investigating.','Secure ferret-proof environment, supervised play, species-appropriate diet, enrichment and routine veterinary care.',['fancy-rat','rabbit']),
  item('african-pygmy-hedgehog','small-animals','African Pygmy Hedgehog','Small mammal · Companion','Small nocturnal mammal kept in some regions as a companion, with specialized environmental and dietary needs.',['Nocturnal','Solitary','Small mammal'],'Usually active at night, exploring, sniffing and foraging.','Stable warm environment, secure enclosure, enrichment, appropriate diet and regular cleaning. Check local rules before keeping exotic species.',['chinchilla','ferret']),

  item('betta','fish-aquatic','Betta','Freshwater fish · Labyrinth fish','Small freshwater fish known for flowing fins in many varieties and territorial behavior, especially among males.',['Freshwater','Colorful','Territorial'],'Often patrols its environment and uses the surface for air through its labyrinth organ.','Stable heated, filtered aquarium appropriate to the fish, clean water, hiding places and a varied suitable diet.',['guppy','neon-tetra','corydoras'],true),
  item('guppy','fish-aquatic','Guppy','Freshwater fish · Livebearer','Small, active freshwater fish known for colorful males and live-bearing reproduction.',['Freshwater','Community','Livebearer'],'Active throughout the aquarium and often spends time in open water and around plants.','Stable water parameters, filtration, suitable temperature, plants or cover and an appropriate community setup.',['betta','platy','molly']),
  item('neon-tetra','fish-aquatic','Neon Tetra','Freshwater fish · Schooling','Small schooling freshwater fish recognized by a bright horizontal stripe and preference for groups.',['Freshwater','Schooling','Small'],'Often moves together with other members of its group and uses planted spaces for cover.','Keep an appropriate group, stable clean water, suitable filtration and planted or structured habitat.',['guppy','corydoras','zebra-danio']),
  item('corydoras','fish-aquatic','Corydoras Catfish','Freshwater fish · Bottom-dweller','Small social bottom-dwelling catfish that often forage along the substrate.',['Freshwater','Bottom-dweller','Social'],'Frequently explores the bottom, sifting through substrate and resting among plants or shelter.','Keep an appropriate social group, use smooth substrate, provide hiding places and maintain excellent water quality.',['neon-tetra','guppy','bristlenose-pleco']),
  item('zebra-danio','fish-aquatic','Zebra Danio','Freshwater fish · Schooling','Hardy small schooling fish known for active swimming and distinctive horizontal stripes.',['Freshwater','Schooling','Active'],'Constantly moves through the water column and often explores the full aquarium.','Provide swimming space, a compatible group, stable water quality and secure cover.',['neon-tetra','guppy','white-cloud-mountain-minnow']),
  item('platy','fish-aquatic','Platy','Freshwater fish · Livebearer','Peaceful livebearing freshwater fish available in many colors and patterns.',['Freshwater','Community','Livebearer'],'Active and social, commonly moving through plants and open water.','Stable water quality, filtration, plants or cover and a suitable community aquarium.',['guppy','molly','swordtail']),
  item('molly','fish-aquatic','Molly','Freshwater fish · Livebearer','Popular livebearing fish with many body and color forms and generally active behavior.',['Freshwater','Community','Livebearer'],'Often explores open water and planted areas while feeding throughout the aquarium.','Appropriate aquarium volume, filtration, stable water conditions and a compatible social group.',['guppy','platy','swordtail']),
  item('bristlenose-pleco','fish-aquatic','Bristlenose Pleco','Freshwater fish · Catfish','Bottom-oriented freshwater catfish known for bristle-like facial growths in mature males.',['Freshwater','Bottom-dweller','Algae grazer'],'Often attaches to surfaces, explores wood and shelter and becomes more active around lower light.','Provide hiding places, suitable driftwood where appropriate, clean water and species-appropriate food rather than relying only on algae.',['corydoras','zebra-danio']),

  item('leopard-gecko','reptiles','Leopard Gecko','Reptile · Gecko','Small terrestrial gecko commonly kept as a companion animal and known for a manageable adult size.',['Gecko','Nocturnal','Insect-eating'],'Often becomes active around dusk and night, exploring and hunting insects.','Appropriate temperature gradient, secure enclosure, hides, suitable substrate and correctly supplemented food.',['crested-gecko','bearded-dragon'],true),
  item('crested-gecko','reptiles','Crested Gecko','Reptile · Gecko','Arboreal gecko known for climbing ability, large eyes and specialized toe structures.',['Gecko','Arboreal','Nocturnal'],'Often climbs and explores vertically, becoming more active during evening hours.','Vertical enclosure, appropriate humidity and ventilation, climbing surfaces, hides and species-appropriate diet.',['leopard-gecko','bearded-dragon']),
  item('bearded-dragon','reptiles','Bearded Dragon','Reptile · Lizard','Diurnal Australian lizard commonly kept as a companion and known for a curious, observant demeanor.',['Lizard','Diurnal','Omnivorous'],'Often basks, explores and watches activity around its environment during daylight hours.','Proper UVB and heat setup, suitable enclosure size, varied age-appropriate diet, hydration and regular cleaning.',['leopard-gecko','crested-gecko']),
  item('corn-snake','reptiles','Corn Snake','Reptile · Snake','Nonvenomous North American snake commonly kept by experienced companion-animal keepers.',['Snake','Nonvenomous','Nocturnal'],'Often explores, climbs and investigates scents, with activity varying by temperature and time of day.','Escape-proof enclosure, appropriate thermal gradient, hides, humidity appropriate to the species and suitable feeding under responsible adult care.',['ball-python','leopard-gecko']),
  item('red-eared-slider','reptiles','Red-eared Slider','Reptile · Aquatic turtle','Semi-aquatic turtle species with substantial adult size and long-term care requirements.',['Aquatic turtle','Long-lived','Semi-aquatic'],'Often alternates between swimming and basking and can be active during daylight.','Large aquatic habitat, strong filtration, basking area, appropriate UVB and heat, balanced diet and long-term planning. Never release captive turtles into the wild.',['bearded-dragon','corn-snake']),
];

export const journalEntries = [
  { id: 'choose-a-pet', title: 'How to choose a pet that fits your life', text: 'Temperament, activity, space, time and long-term commitment matter more than appearance alone.' },
  { id: 'daily-routine', title: 'What good daily pet care looks like', text: 'A useful routine combines food, water, hygiene, enrichment, observation and a safe environment.' },
  { id: 'understanding-behavior', title: 'Learn the animal before changing the behavior', text: 'Understanding normal species and breed behavior makes everyday care calmer and more responsible.' },
  { id: 'wildlife-is-different', title: 'Pets and wildlife are not the same thing', text: 'Some animals are best admired in nature. Responsible care includes knowing when an animal should remain wild.' },
];

export const typeLabel = Object.fromEntries(categories.map((category) => [category.id, category.label]));

export function getRecord(id) {
  return records.find((record) => record.id === id) || null;
}

export function getCategory(id) {
  return categories.find((category) => category.id === id) || null;
}

export function getRelated(record, limit = 6) {
  if (!record) return [];
  const explicit = record.related.map((id) => getRecord(id)).filter(Boolean);
  const sameType = records.filter((item) => item.type === record.type && item.id !== record.id && !record.related.includes(item.id));
  return [...explicit, ...sameType].slice(0, limit);
}
