import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, ArrowRight, Bookmark, Bird, Cat, Dog, Fish, Globe2, PawPrint, Rabbit, Search, Turtle } from 'lucide-react';
import { categories, getCategory, getRecord, getRelated, journalEntries, records, typeLabel } from './data';
import { countries, getCountry, getCountryRecords } from './countries';
import { enrichRecord, getImageTitles } from './petDetails';
import { loadSaved, saveSaved } from './storage';
import './styles.css';
import './discover.css';

const icons = { dogs: Dog, cats: Cat, birds: Bird, 'small-animals': Rabbit, 'fish-aquatic': Fish, reptiles: Turtle };
const richRecords = records.map(enrichRecord);
const byId = new Map(richRecords.map((r) => [r.id, r]));
const quickSearches = ['Labrador Retriever', 'Maine Coon', 'Budgerigar', 'Guinea Pig', 'Betta', 'Swallows'];

function route() {
  const parts = (window.location.pathname.replace(/\/+$/, '') || '/').split('/').filter(Boolean);
  if (parts[0] === 'pet' || parts[0] === 'entity') return { page: 'pet', id: parts[1] };
  if (parts[0] === 'category') return { page: 'category', id: parts[1] };
  if (parts[0] === 'country') return { page: 'country', id: parts[1] };
  if (parts[0] === 'countries') return { page: 'countries' };
  if (parts[0] === 'saved') return { page: 'saved' };
  if (parts[0] === 'explore') return { page: 'explore' };
  return { page: 'home' };
}
function go(to) { window.history.pushState({}, '', to); window.dispatchEvent(new PopStateEvent('popstate')); window.scrollTo({ top: 0, behavior: 'smooth' }); }

function useAnimalImage(record) {
  const [source, setSource] = useState('');
  useEffect(() => {
    let active = true;
    setSource('');
    const titles = getImageTitles(record);
    (async () => {
      for (const title of titles) {
        try {
          const res = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title.replace(/ /g, '_'))}`);
          if (!res.ok) continue;
          const data = await res.json();
          const image = data?.originalimage?.source || data?.thumbnail?.source;
          if (image) { if (active) setSource(image); return; }
        } catch {}
      }
    })();
    return () => { active = false; };
  }, [record.id]);
  return source;
}
function AnimalImage({ record, className = '' }) {
  const [failed, setFailed] = useState(false);
  const image = useAnimalImage(record);
  useEffect(() => setFailed(false), [record.id]);
  if (!image || failed) return <div className={`animal-image animal-image-fallback ${className}`} aria-label={`${record.name} illustration`}><PawPrint size={30}/><span>{record.name}</span></div>;
  return <img className={`animal-image ${className}`} src={image} alt={`${record.name}`} loading="lazy" onError={() => setFailed(true)} />;
}
function CountryImage({ country, className = '' }) { const record = byId.get(country.recordIds[0]); return record ? <AnimalImage record={record} className={className}/> : <div className={`animal-image animal-image-fallback ${className}`}><Globe2/></div>; }

function Header({ savedCount }) { return <header className="nav"><a className="logo" href="/" onClick={(e)=>{e.preventDefault();go('/')}}><span className="logo-mark">P</span><span>discover.pet</span></a><nav><a href="/explore" onClick={(e)=>{e.preventDefault();go('/explore')}}>Explore</a><a href="/countries" onClick={(e)=>{e.preventDefault();go('/countries')}}>Countries</a><a href="/#categories">Animals</a><a href="/#journal">Guides</a></nav><button className="saved" onClick={()=>go('/saved')}><Bookmark size={16}/> Saved <span>{savedCount}</span></button></header>; }
function SearchBox({ value, setValue }) { return <form className="searchbox" onSubmit={(e)=>{e.preventDefault();go(`/explore${value.trim()?`?q=${encodeURIComponent(value.trim())}`:''}`)}}><Search size={20}/><input aria-label="Search animals" value={value} onChange={e=>setValue(e.target.value)} placeholder="Search breeds, species, habits or care…"/><kbd>⌘ K</kbd></form>; }

function Home({ query, setQuery }) { return <><section className="hero"><div className="eyebrow"><PawPrint size={15}/> A clear guide to life with animals</div><h1>Understand the animal<br/><em>before you choose one.</em></h1><p className="hero-copy">Explore breeds and species, learn their habits, discover where they come from and understand the everyday care they need.</p><SearchBox value={query} setValue={setQuery}/><div className="quick"><span>Try:</span>{quickSearches.map(x=><button key={x} onClick={()=>go(`/explore?q=${encodeURIComponent(x)}`)}>{x}</button>)}</div></section><section className="featured"><div className="section-head"><div><span className="label">Featured animal guides</span><h2>Start with a species you know.</h2></div><button className="text-link" onClick={()=>go('/explore')}>View all <ArrowRight size={16}/></button></div><div className="feature-grid">{richRecords.filter(r=>r.featured).map(r=><article className="feature-card" key={r.id} onClick={()=>go(`/pet/${r.id}`)}><AnimalImage record={r} className="feature-image"/><span>{typeLabel[r.type]}</span><h3>{r.name}</h3><p>{r.overview}</p><div className="card-foot"><small>{r.meta}</small><ArrowRight size={17}/></div></article>)}</div></section><CountrySection/><section className="directory" id="categories"><div className="section-head"><div><span className="label">Explore animals</span><h2>Choose a direction.</h2></div></div><div className="category-grid">{categories.map(c=>{const Icon=icons[c.id]||PawPrint;return <button className="category" key={c.id} onClick={()=>go(`/category/${c.id}`)}><span className="cat-icon"><Icon size={19}/></span><span><strong>{c.label}</strong><small>{c.text}</small></span><ArrowRight size={16}/></button>})}</div></section><section className="journal" id="journal"><div><span className="label">Pet Journal</span><h2>Useful ideas for<br/>better animal care.</h2></div><div className="journal-list">{journalEntries.map((e,i)=><article key={e.id}><div><span className="journal-num">{String(i+1).padStart(2,'0')}</span><h3>{e.title}</h3><p>{e.text}</p></div><ArrowRight size={18}/></article>)}</div></section></>; }
function CountrySection(){return <section className="directory country-directory"><div className="section-head"><div><span className="label">Discover by origin</span><h2>Animals have stories tied to places.</h2><p>Explore breeds by country, region and history.</p></div><button className="text-link" onClick={()=>go('/countries')}>All countries <ArrowRight size={16}/></button></div><div className="country-grid">{countries.slice(0,3).map(c=><CountryCard country={c} key={c.id}/>)}</div></section>}
function CountryCard({country}){return <button className="country-card" onClick={()=>go(`/country/${country.id}`)}><CountryImage country={country}/><div className="country-overlay"><span className="country-flag">{country.flag}</span><strong>{country.name}</strong><small>{country.recordIds.length} profiles · {country.regions.slice(0,3).join(' · ')}</small></div></button>}

function Results({ results, saved, toggleSave }){return <div className="result-grid">{results.map(r=><article className="result-card" key={r.id}><button className="result-main" onClick={()=>go(`/pet/${r.id}`)}><AnimalImage record={r} className="result-avatar"/><div><span className="result-type">{typeLabel[r.type]}</span><h3>{r.name}</h3><p>{r.overview}</p><small>{r.meta}</small><div className="tags">{r.tags.map(t=><span key={t}>{t}</span>)}</div></div></button><button className={`bookmark ${saved.includes(r.id)?'on':''}`} onClick={()=>toggleSave(r.id)} aria-label="Save guide"><Bookmark size={17}/></button></article>)}</div>}
function Explore({query,setQuery,results,saved,toggleSave}){return <section className="results-page"><div className="page-hero"><button className="back-link" onClick={()=>go('/')}><ArrowLeft size={16}/> Home</button><span className="label">Animal discovery index</span><h1>Explore pets & animals.</h1><p>Search across breeds, species, habits, care topics and profile notes.</p><SearchBox value={query} setValue={setQuery}/></div><div className="section-head results-head"><h2>{results.length} {results.length===1?'guide':'guides'}</h2></div>{results.length?<Results results={results} saved={saved} toggleSave={toggleSave}/>:<div className="empty"><Search size={28}/><h3>Nothing found yet.</h3><p>Try a breed, species, habit or broader category.</p></div>}</section>}
function CategoryPage({category,saved,toggleSave}){const results=richRecords.filter(r=>r.type===category.id);const Icon=icons[category.id]||PawPrint;return <section className="results-page"><div className="page-hero"><button className="back-link" onClick={()=>go('/')}><ArrowLeft size={16}/> Home</button><div className="category-hero-icon"><Icon size={22}/></div><span className="label">{category.label}</span><h1>{category.label}.</h1><p>{category.text}</p></div><Results results={results} saved={saved} toggleSave={toggleSave}/></section>}
function CountriesPage(){return <section className="results-page"><div className="page-hero"><button className="back-link" onClick={()=>go('/')}><ArrowLeft size={16}/> Home</button><span className="label">Global animal origins</span><h1>Discover by country.</h1><p>Follow breeds through geography, history, regions and animal traditions.</p></div><div className="country-grid country-grid-large">{countries.map(c=><CountryCard country={c} key={c.id}/>)}</div></section>}
function CountryPage({country,saved,toggleSave}){const rs=getCountryRecords(country,records).map(enrichRecord);return <section className="results-page"><div className="country-hero"><button className="back-link" onClick={()=>go('/countries')}><ArrowLeft size={16}/> Countries</button><CountryImage country={country}/><div><span className="country-flag">{country.flag}</span><span className="label">Country guide</span><h1>{country.name}.</h1><p>{country.intro}</p><div className="country-regions">{country.regions.map(x=><span key={x}>{x}</span>)}</div></div></div><div className="section-head results-head"><div><span className="label">Breeds & animals</span><h2>Profiles connected to {country.name}</h2></div></div><Results results={rs} saved={saved} toggleSave={toggleSave}/><div className="country-note"><Globe2 size={20}/><p><strong>Origin matters.</strong> discover.pet separates origin, regional history and modern popularity so geographic relationships stay educational.</p></div></section>}

function PetPage({record,saved,toggleSave}){const related=getRelated(record,6).map(r=>byId.get(r.id)).filter(Boolean);return <article className="pet-page"><button className="back-link" onClick={()=>go('/explore')}><ArrowLeft size={16}/> Explore</button><div className="pet-hero"><AnimalImage record={record} className="pet-cover"/><div className="pet-intro"><span className="label">{typeLabel[record.type]}</span><h1>{record.name}</h1><p className="pet-meta">{record.meta}</p><p className="lead">{record.overview}</p><button className={`save-large ${saved.includes(record.id)?'saved-state':''}`} onClick={()=>toggleSave(record.id)}>{saved.includes(record.id)?'Saved guide':'Save guide'} <Bookmark size={16}/></button></div></div><div className="pet-layout"><main><section className="content-section"><span className="label">Overview</span><h2>Getting to know {record.name}</h2><p>{record.overview}</p></section><section className="content-section two-col"><div><span className="label">Behavior & personality</span><h2>How this animal tends to experience the day</h2><p>{record.behaviorGuide}</p></div><div className="info-panel"><strong>Typical habits</strong><p>{record.habits}</p></div></section><section className="content-section"><span className="label">Daily care</span><h2>What responsible care looks like</h2><p>{record.careGuide}</p><div className="care-grid"><div><strong>Environment</strong><p>{record.habitatGuide}</p></div><div><strong>Before choosing</strong><p>{record.choosingGuide}</p></div></div></section>{record.note&&<section className="important"><strong>Important note</strong><p>{record.note}</p></section>}<section className="content-section"><span className="label">Profile highlights</span><h2>Key characteristics</h2><div className="highlight-list">{record.tags.map((t,i)=><div key={t}><span>0{i+1}</span><strong>{t}</strong><p>{record.facts[i]}</p></div>)}</div></section></main><aside><div className="side-card"><span className="label">Quick facts</span><h3>{record.name}</h3><dl><dt>Category</dt><dd>{typeLabel[record.type]}</dd><dt>Profile</dt><dd>{record.meta}</dd><dt>Traits</dt><dd>{record.tags.join(' · ')}</dd></dl></div>{related.length>0&&<div className="side-card"><span className="label">Related guides</span>{related.map(r=><button className="related-item" key={r.id} onClick={()=>go(`/pet/${r.id}`)}><span>{r.name}</span><ArrowRight size={14}/></button>)}</div>}</aside></div></article>}
function SavedPage({saved,toggleSave}){const rs=richRecords.filter(r=>saved.includes(r.id));return <section className="results-page"><div className="page-hero"><button className="back-link" onClick={()=>go('/')}><ArrowLeft size={16}/> Home</button><span className="label">Your collection</span><h1>Saved guides.</h1><p>Keep animal profiles you want to revisit.</p></div>{rs.length?<Results results={rs} saved={saved} toggleSave={toggleSave}/>:<div className="empty"><Bookmark size={28}/><h3>Nothing saved yet.</h3><p>Open an animal guide and use Save guide to build your collection.</p></div>}</section>}

function App(){const [r,setR]=useState(route);const [query,setQuery]=useState(()=>new URLSearchParams(location.search).get('q')||'');const [saved,setSaved]=useState(loadSaved);useEffect(()=>{const f=()=>{setR(route());setQuery(new URLSearchParams(location.search).get('q')||'')};addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);useEffect(()=>saveSaved(saved),[saved]);useEffect(()=>{const f=e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.querySelector('.searchbox input')?.focus()}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);const toggleSave=id=>setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);const q=query.trim().toLowerCase();const results=useMemo(()=>richRecords.filter(x=>!q||x.searchText.toLowerCase().includes(q)),[q]);let content;if(r.page==='pet'&&byId.has(r.id))content=<PetPage record={byId.get(r.id)} saved={saved} toggleSave={toggleSave}/>;else if(r.page==='explore')content=<Explore query={query} setQuery={setQuery} results={results} saved={saved} toggleSave={toggleSave}/>;else if(r.page==='category'&&getCategory(r.id))content=<CategoryPage category={getCategory(r.id)} saved={saved} toggleSave={toggleSave}/>;else if(r.page==='countries')content=<CountriesPage/>;else if(r.page==='country'&&getCountry(r.id))content=<CountryPage country={getCountry(r.id)} saved={saved} toggleSave={toggleSave}/>;else if(r.page==='saved')content=<SavedPage saved={saved} toggleSave={toggleSave}/>;else content=<Home query={query} setQuery={setQuery}/>;return <div className="app"><Header savedCount={saved.length}/><main id="top">{content}</main><footer><a className="logo" href="/" onClick={e=>{e.preventDefault();go('/')}}><span className="logo-mark">P</span><span>discover.pet</span></a><p>Learn. Care. Understand.</p><span>© 2026 discover.pet</span></footer></div>}

createRoot(document.getElementById('root')).render(<App/>);
